/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Admin: () => import('#controllers/admin_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Comments: () => import('#controllers/comments_controller'),
  Executions: () => import('#controllers/executions_controller'),
  Groups: () => import('#controllers/groups_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Posts: () => import('#controllers/posts_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Users: () => import('#controllers/users_controller'),
  Votes: () => import('#controllers/votes_controller'),
  Ai: () => import('#controllers/ai_controller'),
}
